# Generated by Django 3.1.7 on 2021-02-23 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArcherClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Klassekode')),
                ('description', models.CharField(max_length=50, verbose_name='Klassenavn')),
            ],
            options={
                'verbose_name': 'Konkurranseklasse',
                'verbose_name_plural': 'Konkurranseklasser',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('host', models.CharField(default='Norges Bueskytterforbund', max_length=100, verbose_name='Arrangør')),
                ('start_date', models.DateTimeField(verbose_name='Konkurransestart')),
                ('end_date', models.DateTimeField(verbose_name='Konkurranseslutt')),
                ('signup_deadline', models.DateTimeField(verbose_name='Påmeldingsfrist')),
                ('allowed_classes', models.ManyToManyField(to='signups.ArcherClass', verbose_name='Tillate klasser')),
            ],
            options={
                'verbose_name': 'Konkurranse',
                'verbose_name_plural': 'Konkurranser',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('archer_id', models.CharField(max_length=10, verbose_name='IANSEO-nummer')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('email', models.EmailField(max_length=254, verbose_name='E-post')),
                ('archer_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.archerclass', verbose_name='Konkurranseklasse')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.competition', verbose_name='Konkurranse')),
            ],
            options={
                'verbose_name': 'Påmelding',
                'verbose_name_plural': 'Påmeldinger',
            },
        ),
        migrations.CreateModel(
            name='ResultDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorecard', models.ImageField(upload_to='uploads/scorecards/', verbose_name='Scorekort')),
                ('proof_image1', models.ImageField(upload_to='uploads/proof_images/', verbose_name='Bildebevis 1')),
                ('proof_image2', models.ImageField(blank=True, null=True, upload_to='uploads/proof_images/', verbose_name='Bildebevis 2')),
                ('proof_image3', models.ImageField(blank=True, null=True, upload_to='uploads/proof_images/', verbose_name='Bildebevis 3')),
                ('proof_image4', models.ImageField(blank=True, null=True, upload_to='uploads/proof_images/', verbose_name='Bildebevis 4')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.signup', verbose_name='Påmelding')),
            ],
            options={
                'verbose_name': 'Resultat',
                'verbose_name_plural': 'Resultater',
            },
        ),
    ]
