# Generated by Django 3.1.7 on 2021-04-16 14:01

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archerclass',
            options={'ordering': ('code',), 'verbose_name': 'Konkurranseklasse', 'verbose_name_plural': 'Konkurranseklasser'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ('archer_id',), 'verbose_name': 'Påmelding', 'verbose_name_plural': 'Påmeldinger'},
        ),
        migrations.AlterField(
            model_name='resultdelivery',
            name='proof_image1',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/proof_images/', verbose_name='Bildebevis 1'),
        ),
        migrations.AlterField(
            model_name='resultdelivery',
            name='proof_image2',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='uploads/proof_images/', verbose_name='Bildebevis 2'),
        ),
        migrations.AlterField(
            model_name='resultdelivery',
            name='proof_image3',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='uploads/proof_images/', verbose_name='Bildebevis 3'),
        ),
        migrations.AlterField(
            model_name='resultdelivery',
            name='proof_image4',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='uploads/proof_images/', verbose_name='Bildebevis 4'),
        ),
        migrations.AlterField(
            model_name='resultdelivery',
            name='scorecard',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/scorecards/', verbose_name='Scorekort'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='archer_id',
            field=models.CharField(max_length=10, verbose_name='Skytternummer'),
        ),
    ]
