version: "3.9"

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nbfsignup
      - POSTGRES_PASSWORD=nbfsignup
      - POSTGRES_DB=nbfsignup
    volumes:
      - database-data:/var/lib/postgresql/data


  app:
    image: nbfsignup:latest
    restart: unless-stopped
    environment:
      - DJANGO_SUPERUSER_USERNAME=dagolap
      - DJANGO_SUPERUSER_EMAIL=dagolav@prestegarden.com
      - DJANGO_SUPERUSER_PASSWORD=test
      - SECRET_KEY=kjaskdja
      - DATABASE_URL=postgres://nbfsignup:nbfsignup@db:5432/nbfsignup
      - ALLOWED_HOSTS=localhost
      - STATIC_ROOT=/staticfiles
      - MEDIA_ROOT=/mediafiles
    volumes:
      - static-volume:/staticfiles
      - media-volume:/mediafiles
    depends_on:
      - db


  nginx:
    image: nginx:1.19.7-alpine
    restart: unless-stopped
    volumes:
      - static-volume:/staticfiles
      - media-volume:/mediafiles
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  database-data:
  static-volume:
  media-volume:
