version: "3.9"

services:
  db:
    image: mariadb:10.5.9-focal
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=asdfg
      - MYSQL_DATABASE=nbfsignup
      - MYSQL_USER=nbfsignup
      - MYSQL_PASSWORD=nbfsignup
    volumes:
      - database-data:/var/lib/mysql


  app:
    image: nbfsignup:latest
    restart: unless-stopped
    environment:
      - DJANGO_SUPERUSER_USERNAME=dagolap
      - DJANGO_SUPERUSER_EMAIL=dagolav@prestegarden.com
      - DJANGO_SUPERUSER_PASSWORD=test
      - SECRET_KEY=kjaskdja
      - DATABASE_URL=mysql://nbfsignup:nbfsignup@db:3306/nbfsignup
      - DATABASE_SSL=True
      - ALLOWED_HOSTS=localhost
      - STATIC_ROOT=/staticfiles
      - MEDIA_ROOT=/mediafiles
    volumes:
      - static-volume:/staticfiles
      - media-volume:/mediafiles
    depends_on:
      - db


  nginx:
    image: nginx:1.19.7-alpine
    restart: unless-stopped
    volumes:
      - static-volume:/staticfiles
      - media-volume:/mediafiles
      - ./nginx-files/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  database-data:
  static-volume:
  media-volume:
